### ISSUE TITLE
Assets for coreLang

### ISSUE THREAD

**Issue by simonhacks** [mal-lang/coreLang#1]
* Network
** Network
*** Medium
**** Radio
**** Electric
**** Light
*** Principle
**** Point to Point (1 to n)
**** Broadcast (n to m)
**** Ring (?)
** Data flow
*** Encryption
* Vulnerabilities (Own class needed? Isn't it included in machines per se?)
* IAM
** Accounts
*** CRUD on Data(flow)
** User (n to m Accounts)
* Machines
** Machine (can run on other machine)
** Router (Network connecting)
* Data
** Data
*** CRUD (Encryption)

**Comment by skatsikeas** [comment]
Here are my notes for today:

# Machines:
(Hardware) Machine
Instance (Either physical or virtual)
Networking Machine (e.g. Router, Firewall, etc.)

# Data/Info:
Data
Information (contained in Data or Connection or Machine)

# User/IAM:
Account/Service Account
User/Identity
Role/Privilleges (because one service account could have many roles but only one user)

# Network:
Network
- Wired
- Wireless

Connection or Dataflow(?)
- Point-to-Point
- Broadcast

Network Clients & Servers

# Software/Vulnerabilities:
Software (running on a Machine)
Vulnerabilities (no need to be an asset, it will be an attack step on Machine/Software)

--------------------------------
And some ideas on attack steps:
A Machine could be discoverable (discover) instead of connectable (connect)
Access could remain as is for legitimate access (leg. Access -> access) but
We can have compromisedAccess for attacks
